### PR TITLE
Add Javadoc badge with automatic version detection

### PR DESCRIPTION
**Pull request by valery1707**

### CODE REVIEW

**Comment by dmarkov** [comment]
@valery1707 Thanks, I will ask someone to do a code review here, thanks for your pull request

**Comment by dmarkov** [comment]
@yegor256 review this pull request please, it is rather short for a full review

**Comment by yegor256** [comment]
@rultor merge

**Comment by dmarkov** [comment]
@yegor256 thanks, paid, **16 mins** to your account, payment ID is `000-fce4e0f9`, task took 25 hours and 2 mins to complete

you're getting extra minutes here (c=1)

+16 added to your rating, at the moment it is: [+4563](http://www.netbout.com/b/35008?open=rating)

**Comment by dmarkov** [comment]
@rultor please deploy

**Pull request merged**
